---
abstract: 'A validator for IBANs.'
author:
  - 'Abe Timmerman <abeltje@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.56
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-IBAN-Validator
no_index:
  directory:
    - t
    - inc
requires:
  Hash::Util: 0
version: 0.01
